#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Error
Version  : 0.17026
Release  : 17
URL      : https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/Error-0.17026.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/Error-0.17026.tar.gz
Summary  : 'Error/exception handling in an OO-ish way'
Group    : Development/Tools
License  : Artistic-1.0-Perl GPL-2.0
Requires: perl-Error-license
Requires: perl-Error-man
BuildRequires : perl(Module::Build)

%description
This archive contains the distribution Error,
version 0.17026:
Error/exception handling in an OO-ish way

%package license
Summary: license components for the perl-Error package.
Group: Default

%description license
license components for the perl-Error package.


%package man
Summary: man components for the perl-Error package.
Group: Default

%description man
man components for the perl-Error package.


%prep
%setup -q -n Error-0.17026

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-Error
cp LICENSE %{buildroot}/usr/share/doc/perl-Error/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Error.pm
/usr/lib/perl5/site_perl/5.26.1/Error/Simple.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-Error/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/Error.3
/usr/share/man/man3/Error::Simple.3
