#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Error
Version  : 0.17024
Release  : 9
URL      : http://search.cpan.org/CPAN/authors/id/S/SH/SHLOMIF/Error-0.17024.tar.gz
Source0  : http://search.cpan.org/CPAN/authors/id/S/SH/SHLOMIF/Error-0.17024.tar.gz
Summary  : 'Error/exception handling in an OO-ish way'
Group    : Development/Tools
License  : Artistic-1.0-Perl GPL-2.0
Requires: perl-Error-doc

%description
NAME
Error - Error/exception handling in an OO-ish way
DESCRIPTION
The Error package provides two interfaces. Firstly Error provides
a procedural interface to exception handling. Secondly Error is a
base class for errors/exceptions that can either be thrown, for
subsequent catch, or can simply be recorded.

%package doc
Summary: doc components for the perl-Error package.
Group: Documentation

%description doc
doc components for the perl-Error package.


%prep
%setup -q -n Error-0.17024

%build
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make V=1  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.24.0/Error.pm
/usr/lib/perl5/site_perl/5.24.0/Error/Simple.pm

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
